# Generated by Django 5.0.4 on 2024-04-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=100)),
                ('manufacturer_year', models.CharField(max_length=10)),
                ('bought_year', models.CharField(max_length=10)),
                ('working_condition', models.CharField(max_length=20)),
            ],
        ),
    ]
